# Generated by Django 4.2 on 2023-04-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='ativos',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ativos',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='servico',
            name='ativos',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
